kind = "mobile"
previewPath = "/"
title = "Site Yönetim Sistemi"
version = "1.0.0"
id = "default-mobile-app"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
name = "expo"
paths = [ "/" ]
localPort = 18115

[services.development]
run = "pnpm --filter @workspace/mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/mobile", "run", "serve" ]

[services.env]
PORT = "18115"
BASE_PATH = "/"
